# Generated by Django 5.0.1 on 2024-01-16 17:56

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_groups(apps, schema_editor):
    Group.objects.create(name='Customers')
    Group.objects.create(name='Sellers')

    product_content_type, _ = ContentType.objects.get_or_create(
        model='product', app_label='enigma_ecommerce'
    )

    customers_group, _ = Group.objects.get_or_create(name='Customers')
    sellers_group, _ = Group.objects.get_or_create(name='Sellers')

    view_product_permission, _ = Permission.objects.get_or_create(
        codename='view_product',
        content_type=product_content_type,
    )
    customers_group.permissions.add(view_product_permission)

    modify_product_permission, _ = Permission.objects.get_or_create(
        codename='modify_product',
        content_type=product_content_type,
    )
    add_product_permission, _ = Permission.objects.get_or_create(
        codename='add_product', content_type=product_content_type
    )
    delete_product_permission, _ = Permission.objects.get_or_create(
        codename='delete_product', content_type=product_content_type
    )

    sellers_group.permissions.add(
        add_product_permission, modify_product_permission, delete_product_permission
    )


class Migration(migrations.Migration):

    dependencies = [
        ('enigma_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
